version: "3.8"

services:
  nifi:
    image: apache/nifi:1.28.0
    container_name: nifi-processor
    restart: unless-stopped
    ports:
      - "8080:8080"  # NiFi web interface
      - "8443:8443"  # NiFi web interface (Secure)
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_SENSITIVE_PROPS_KEY=changeme123456789
      - NIFI_SINGLE_USER_CREDENTIALS_USERNAME=admin
      - NIFI_SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - nifi-database_repository:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content_repository:/opt/nifi/nifi-current/content_repository
      - nifi-provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi-state:/opt/nifi/nifi-current/state
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-logs:/opt/nifi/nifi-current/logs
      - ./target/json2pdf-processor-1.0.nar:/opt/nifi/nifi-current/lib/json2pdf-processor-1.0.nar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/nifi/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  nifi-database_repository:
  nifi-flowfile_repository:
  nifi-content_repository:
  nifi-provenance_repository:
  nifi-state:
  nifi-conf:
  nifi-logs:
